### ISSUE TITLE
Dossier patient/Ajouter/Rechercher le tuteur en utilisant leur CIN au lieu de leur nom

### ISSUE THREAD

**Issue by Jalil-Betroji** [cnmh/app#255]
## Description de bug
Lors de l'affichage de la liste des tuteurs : 
- Recherche le  tuteur utilisant leur   CIN 
## Production de l'erreur  
- Accéder au dossier beneficiers 
- Clicker sur ajouter  
- Sur la table de la liste des tuteurs, la barre de recherche devrait permettre de rechercher à l'aide du CIN

## Solution 
- Modifier les paramètres de récupération des données selon la méthode 'where'

**Comment by Yasmine-daifane** [comment]
a ete fait dans une autre version
